version: '3.8'
name: ljas-notes-api
services:
    db:
        build:
            dockerfile: db.Dockerfile
        image: ljas-notes-api-db
        container_name: ljas-notes-api-db
        restart: always
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        env_file: .env
        command: '-p ${POSTGRES_PORT}'
        volumes:
            - ljas-notes-db-data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -p ${POSTGRES_PORT}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build: .
        image: ljas-notes-api
        container_name: ljas-notes-api
        depends_on:
            db:
                condition: service_healthy
        restart: always
        ports:
            - '${PORT_EXPRESS}:${PORT_EXPRESS}'
            - '${PORT_PRISMA_STUDIO}:${PORT_PRISMA_STUDIO}'
            - '9229:9229' # Exposes Node.js debugger. Also defined in the "start:debug" package.json script.
            - '9230:9230' # Exposes Jest debugger. Also defined in the "test:debug" package.json script.
            - '9231:9231' # Exposes webpack debugger. Also defined in the build debug package.json scripts.
        volumes:
            - .:/code
            - ljas-notes-api-node_modules:/code/node_modules
volumes:
    ljas-notes-db-data:
    ljas-notes-api-node_modules:
