version: '3.8'
services:
    db:
        build:
            dockerfile: db.Dockerfile
        image: ljas-notes-api-db
        container_name: ljas-notes-api-db
        restart: always
        ports:
            - '${PORT_DB}:${PORT_DB}'
        env_file: .env
        volumes:
            - ljas-notes-db-data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build: .
        image: ljas-notes-api
        container_name: ljas-notes-api
        depends_on:
            db:
                condition: service_healthy
        restart: always
        ports:
            - '${PORT_APP}:${PORT_APP}'
            - '${PORT_PRISMA_STUDIO}:${PORT_PRISMA_STUDIO}'
        volumes:
            - .:/code
            - /code/node_modules
volumes:
    ljas-notes-db-data:
