version: '3.8'
name: ljas-starchan
services:
    db:
        build:
            dockerfile: db.Dockerfile
        image: ljas-starchan-db
        container_name: ljas-starchan-db
        restart: always
        ports:
            - '${PORT_DB}:${PORT_DB}'
        env_file: .env
        environment:
            - MONGO_REPLICA_PORT=${PORT_DB}
        volumes:
            - ljas-starchan-db-data:/data/db
        healthcheck:
            test:
                [
                    'CMD',
                    'mongo',
                    'admin',
                    '--port',
                    '${PORT_DB}',
                    '--eval',
                    "db.adminCommand('ping')",
                ]
            interval: 5s
            timeout: 2s
            retries: 20
    app:
        build: .
        image: ljas-starchan
        container_name: ljas-starchan
        restart: always
        ports:
            - '${PORT_EXPRESS}:${PORT_EXPRESS}'
            - '${PORT_DEV_SERVER}:${PORT_DEV_SERVER}'
            - '5555:5555' # Exposes Prisma Studio. Also defined in the "prisma:studio" package.json script.
            - '9229:9229' # Exposes Node.js debugger. Also defined in the "start:debug" package.json script.
            - '9230:9230' # Exposes Jest debugger. Also defined in the "test:debug" package.json script.
            - '9231:9231' # Exposes webpack debugger. Also defined in the build debug package.json scripts.
            - '9323:9323' # Exposes Playwright report. Also defined in the "test:e2e:report" package.json script.
        volumes:
            - .:/code
            - ljas-starchan-node_modules:/code/node_modules
volumes:
    ljas-starchan-db-data:
    ljas-starchan-node_modules:
