version: '3.8'
services:
    db:
        build:
            dockerfile: db.Dockerfile
        image: ljas-starchan-db
        container_name: ljas-starchan-db
        restart: always
        ports:
            - '${PORT_DB}:${PORT_DB}'
        env_file: .env
        volumes:
            - ljas-starchan-db-data:/data/db
        healthcheck:
            test:
                [
                    'CMD',
                    'mongo',
                    'admin',
                    '--port',
                    '${MONGO_REPLICA_PORT}',
                    '--eval',
                    "db.adminCommand('ping')",
                ]
            interval: 5s
            timeout: 2s
            retries: 20
    app:
        build: .
        image: ljas-starchan
        container_name: ljas-starchan
        restart: always
        ports:
            - '${PORT_EXPRESS}:${PORT_EXPRESS}'
            - '${PORT_DEV_SERVER}:${PORT_DEV_SERVER}'
            - '${PORT_PRISMA_STUDIO}:${PORT_PRISMA_STUDIO}'
            - '9229:9229' # Exposes Node.js debugger. Also defined in the "start:debug" package.json script.
            - '9230:9230' # Exposes Jest debugger. Also defined in the "test:debug" package.json script.
            - '9231:9231' # Exposes webpack debugger. Also defined in the build debug package.json scripts.
        volumes:
            - .:/code
            - /code/node_modules
volumes:
    ljas-starchan-db-data:
