version: '3.8'
services:
    app:
        build: .
        image: 'ljas-react-frontend'
        container_name: 'ljas-react-frontend'
        ports:
            - '8080:8080'
        volumes:
            - .:/code
            - /code/node_modules
